// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iolplypruaarbuovcgrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbHBseXBydWFhcmJ1b3ZjZ3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjM5ODEsImV4cCI6MjA3MDEzOTk4MX0.Bwq6YwcvAmJqUZSI9aIDY2vcqcjK1Fc2LzAtsrVIWYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});